# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.PlotSummary": types.PlotSummary,
    "stream_types.PlotSummary": stream_types.PlotSummary,

    "types.SQLQuery": types.SQLQuery,
    "stream_types.SQLQuery": stream_types.SQLQuery,


}